### ISSUE TITLE
PHP notice error: GL_WSDL_PATH already defined

### ISSUE THREAD

**Issue by weisswurstkanone** [translations-com/globallink-connect-api-php#4]
Please change the following line

https://github.com/translations-com/globallink-connect-api-php/blob/master/GLExchange/GLExchange.php#L11

to

if (!defined('GL_WSDL_PATH')) {
    define('GL_WSDL_PATH', __DIR__ . '/pd_ws/wsdl/');
}

Otherwise it is not possible to change the path if php error reporting level prevents this.

**Comment by SergeiTsybulko** [comment]
I've added change you requested
Best regards

**Comment by weisswurstkanone** [comment]
Thanks a lot @SergeiTsybulko ! 👍

**Comment by weisswurstkanone** [comment]
Could you create a new tag as well please?

**Comment by weisswurstkanone** [comment]
Merci!

**Comment by SergeiTsybulko** [comment]
@weisswurstkanone version 4.18.5 created
